import { NextApiRequest, NextApiResponse } from 'next';
export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.json([
    {
      id: 1,
      author: '지원',
      title: '[지원]님의 처방전 입니다!',
      emotion: '슬픔',
      created_at: '2023-04-19',
      commentsCnt: '2',
      bookmarksCnt: '3',
      content: '게시글1',
    },
    {
      id: 2,
      author: '진희',
      title: '[진희]님의 처방전 입니다!',
      emotion: '기쁨',
      created_at: '2023-04-23',
      commentsCnt: '6',
      bookmarksCnt: '30',
      content: '게시글2',
    },
    {
      id: 3,
      author: '지현',
      title: '[지현]님의 처방전 입니다!',
      emotion: '걱정',
      created_at: '2023-06-19',
      commentsCnt: '16',
      bookmarksCnt: '59',
      content: '게시글3',
    },
    {
      id: 4,
      author: '요한',
      title: '[요한]님의 처방전 입니다!',
      emotion: '걱정',
      created_at: '2023-04-19',
      commentsCnt: '2',
      bookmarksCnt: '54',
      content: '게시글4',
    },
    {
      id: 5,
      author: '유경',
      title: '[유경]님의 처방전 입니다!',
      emotion: '슬픔',
      created_at: '2023-04-19',
      commentsCnt: '5',
      bookmarksCnt: '2',
      content: '게시글5',
    },
    {
      id: 6,
      author: '성훈',
      title: '[성훈]님의 처방전 입니다!',
      emotion: '기쁨',
      created_at: '2023-04-19',
      commentsCnt: '9',
      bookmarksCnt: '5',
      content: '게시글6',
    },
    {
      id: 7,
      author: '충진',
      title: '[충진]님의 처방전 입니다!',
      emotion: '슬픔',
      created_at: '2023-04-19',
      commentsCnt: '34',
      bookmarksCnt: '4',
      content: '게시글7',
    },
  ]);
}
